const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connector — ProjectOff</title><style>body{font-family:system-ui;margin:0;background:#111;color:#eee}main{max-width:980px;margin:auto;padding:32px}header{display:flex;justify-content:space-between;align-items:center}nav button,.btn{padding:10px 14px;border:1px solid #444;background:#1d1d1d;color:#fff;border-radius:8px;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}.card{border:1px solid #333;border-radius:12px;padding:18px;background:#171717}.muted{color:#aaa}input,select{width:100%;box-sizing:border-box;padding:11px;margin:6px 0 12px;background:#0d0d0d;color:#fff;border:1px solid #444;border-radius:8px}.row{display:flex;gap:10px;flex-wrap:wrap}.hidden{display:none}.hero{padding:34px 0}.pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#282828;font-size:12px}.drop{border:2px dashed #444;padding:28px;text-align:center;border-radius:12px}.result{display:flex;justify-content:space-between;gap:15px;align-items:center;padding:12px 0;border-bottom:1px solid #292929}</style></head><body><main>
<header><h2>🔌 Connector</h2><nav><button data-page="home">Explore</button> <button data-page="publish">Publish</button> <button data-page="node">My Node</button></nav></header>
<section id="home" class="page"><div class="hero"><h1>A content network powered by users.</h1><p class="muted">Discover published content, connect to an available peer, and stream or download without putting the media itself in the central directory.</p><div class="row"><input id="search" placeholder="Search content…" style="max-width:520px"><button class="btn" id="searchBtn">Search</button></div></div><div class="grid" id="results"></div></section>
<section id="publish" class="page hidden"><h1>Publish content</h1><p class="muted">This MVP publishes metadata. The actual file remains on the user's node.</p><label>Title</label><input id="title"><label>Category</label><select id="category"><option>Video</option><option>Audio</option><option>Files</option></select><label>Description</label><input id="description"><label>Content URL / peer reference</label><input id="contentRef" placeholder="peer/content reference for this MVP"><button class="btn" id="publishBtn">Publish</button><p id="publishMsg"></p></section>
<section id="node" class="page hidden"><h1>My Node</h1><p>Your browser can act as a temporary node while this tab is open.</p><div class="card"><div>Node ID</div><h2 id="nodeId">…</h2><div class="muted">Share this ID with another user for direct connection.</div></div><h3>Connect to peer</h3><input id="peerId" placeholder="Peer ID"><button class="btn" id="connectBtn">Connect</button><p id="connMsg"></p><div class="drop" id="drop">Choose a file to prepare a local share<input type="file" id="file" hidden></div><p class="muted">Direct WebRTC transport is intentionally isolated in this first live slice; this UI establishes the product contract without pretending that a browser can provide durable hosting after it closes.</p></section>
<script>
const pages=[...document.querySelectorAll('.page')];document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{pages.forEach(p=>p.classList.toggle('hidden',p.id!==b.dataset.page));});
const key='projectoff-node-id';let nodeId=localStorage.getItem(key);if(!nodeId){nodeId='node-'+crypto.randomUUID();localStorage.setItem(key,nodeId)}document.querySelector('#nodeId').textContent=nodeId;
async function api(path,opt){const r=await fetch(path,opt);if(!r.ok)throw Error(await r.text());return r.json()}
async function search(){const q=document.querySelector('#search').value;const data=await api('/api/content?q='+encodeURIComponent(q));const el=document.querySelector('#results');el.innerHTML=data.items.map(x=>'<div class="card"><span class="pill">'+x.category+'</span><h3>'+esc(x.title)+'</h3><p class="muted">'+esc(x.description||'')+'</p><div class="muted">Provider: '+esc(x.nodeId)+'</div><button class="btn" onclick="openContent(\''+esc(x.ref)+'\',\''+esc(x.title)+'\',\''+esc(x.mime||'')+'\')">Open</button></div>').join('')||'<p class="muted">No published content yet.</p>'}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
window.openContent=(ref,title,mime)=>{if(ref.startsWith('http'))window.open(ref,'_blank','noopener');else alert('Connector found: '+title+'\\nPeer reference: '+ref+'\\n\\nThe next P2P transport layer will resolve this reference on the provider node.')};
document.querySelector('#searchBtn').onclick=search;search();
document.querySelector('#publishBtn').onclick=async()=>{const payload={title:document.querySelector('#title').value.trim(),category:document.querySelector('#category').value,description:document.querySelector('#description').value.trim(),ref:document.querySelector('#contentRef').value.trim(),nodeId};if(!payload.title||!payload.ref)return document.querySelector('#publishMsg').textContent='Title and peer reference are required.';try{await api('/api/content',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});document.querySelector('#publishMsg').textContent='Published to the directory.';document.querySelector('#title').value='';document.querySelector('#description').value='';document.querySelector('#contentRef').value='';}catch(e){document.querySelector('#publishMsg').textContent='Publish failed: '+e.message}}
document.querySelector('#connectBtn').onclick=()=>{const p=document.querySelector('#peerId').value.trim();document.querySelector('#connMsg').textContent=p?'Peer reference saved for transport handshake: '+p:'Enter a peer ID.'};document.querySelector('#drop').onclick=()=>document.querySelector('#file').click();document.querySelector('#file').onchange=e=>{if(e.target.files[0])document.querySelector('#connMsg').textContent='Selected '+e.target.files[0].name+' ('+e.target.files[0].size+' bytes).'};
</script></main></body></html>`;
const mem=[];
export default {async fetch(req,env){const u=new URL(req.url);if(req.method==='GET'&&u.pathname==='/api/content'){const q=(u.searchParams.get('q')||'').toLowerCase();return Response.json({items:mem.filter(x=>(x.title+' '+x.description+' '+x.category).toLowerCase().includes(q)).slice(-100).reverse()})}if(req.method==='POST'&&u.pathname==='/api/content'){try{const x=await req.json();if(!x.title||!x.ref)return Response.json({error:'title and ref required'},{status:400});mem.push({id:crypto.randomUUID(),createdAt:new Date().toISOString(),...x});return Response.json({ok:true})}catch{return Response.json({error:'invalid json'},{status:400})}}if(req.method==='GET'&&(u.pathname==='/'||u.pathname==='/index.html'))return new Response(html,{headers:{'content-type':'text/html;charset=UTF-8'}});return new Response('Not found',{status:404})}};
